baseURL = 'https://v2.code-input-js.org/'
languageCode = 'en-gb'
title = 'code-input.js'
theme = 'code-input-js'

[params]
   version = 'v2.7.2'

# Just works better with the docs; docs content is quality-and-security-controlled
# by the maintainer.
[markup.goldmark.renderer]
   unsafe = true

# Using client-side highlight.js instead (same as code-input, to avoid redundancy)
[markup.highlight]
   anchorLineNos = false
   codeFences = false
   guessSyntax = false
   hl_Lines = ""
   lineAnchors = ""
   lineNoStart = ""
   lineNos = false
   lineNumbersInTable = false
   noClasses = false
   style = ""
   tabWidth = ""
